/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "ProtoBuf.h"
#include "ProtoBuf_Test.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);

/*=======Test Reset Option=====*/
void resetTest(void);

void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/ProtoBuf.c");

  /* Init tests */
  RUN_TEST(test_ProtoBuf_Create_ReturnsOk, 48);
  RUN_TEST(test_ProtoBuf_Destroy_ReturnsOk, 49);

  /* Overrides the default serialize pointer in the case of static allocation in ram is used */
  RUN_TEST(test_ProtoBuf_Create_serializeIsDefault,52);
  RUN_TEST(test_ProtoBuf_Create_DeserializeIsDefault,53);

  RUN_TEST(test_ProtoBuf_Serialize_ExpectedOutput,55);
  return (UnityEnd());
}
